#! /usr/bin/env sh

prefix='registry.cn-zhangjiakou.aliyuncs.com/highsoft/lockers'
tag=$(TZ=Asia/Shanghai date +%Y%m%d%H%M)
workDir=$(pwd)

remove_images() {
  docker images "$prefix.$1" -a -q | xargs -L1 docker rmi -f
}

build_image_with_dependency() {
  remove_images "$1"
  docker build --build-arg DEPENDENCY="$3" -t $prefix."$1":"$tag" -t $prefix."$1":latest "$2"
}

build_image() {
  remove_images "$1"
  docker build -t $prefix."$1":"$tag" -t $prefix."$1":latest "$2"
}

if ! (mkdir -p build/dependencies && (cd build/dependencies; jar -xf ../libs/*.jar)); then
  echo "Failed to extract content from jar"
  exit 1
fi

if ! (cd "$workDir" && build_image_with_dependency "server" "." "build/dependencies"); then
  echo "Filed to build image 'server'"
  exit 1
fi

if ! (mkdir -p services/client-adapter/build/dependencies && (cd services/client-adapter/build/dependencies; jar -xf ../libs/*.jar)); then
  echo "Failed to extract content from jar"
  exit 1
fi

cd "$workDir" && \
build_image_with_dependency "client.adapter" "services/client-adapter" "services/client-adapter/build/dependencies" && \
build_image "management.webui" "frontends/management.webui"
