#! /usr/bin/env sh

prefix='registry.cn-zhangjiakou.aliyuncs.com/highsoft/lockers'

push_image() {
  docker push "$prefix.$1"
}

if ! (push_image server && push_image client.adapter && push_image management.webui); then
  echo "Failed to push docker images"
  exit 1
fi

CURRENT_DIR=$(pwd)
RELEASE_DIR="$CURRENT_DIR/release"
mkdir -p "$RELEASE_DIR"
if ! (cd "$CURRENT_DIR/frontends/client.webui/dist/electron/lockers-darwin-x64" && zip -r "$RELEASE_DIR/lockers-darwin-x64.zip" ./*); then
  echo "Failed to create lockers-darwin-x64.zip"
  cd "$CURRENT_DIR" || exit 1
  exit 1
fi

if ! (cd "$CURRENT_DIR/frontends/client.webui/dist/electron/lockers-win32-x64" && zip -r "$RELEASE_DIR/lockers-win32-x64.zip" ./*); then
  echo "Failed to create lockers-win32-x64.zip"
  cd "$CURRENT_DIR" || exit 1
  exit 1
fi

if ! (cd "$CURRENT_DIR/services/device-controller/build/cmake/device_controller/windows-x86_64" && zip -r "$RELEASE_DIR/device-controller-win32-x64.zip" device-controller.exe); then
  echo "Failed to create device-controller-win32-x64.zip"
  cd "$CURRENT_DIR" || exit 1
  exit 1
fi

if ! (scp -P 1022 -i /home/gitlab-runner/.ssh/deployer "$RELEASE_DIR/lockers-darwin-x64.zip" root@172.26.70.167:/srv/sftp/test/release && \
scp -P 1022 -i /home/gitlab-runner/.ssh/deployer "$RELEASE_DIR/lockers-win32-x64.zip" root@172.26.70.167:/srv/sftp/test/release && \
scp -P 1022 -i /home/gitlab-runner/.ssh/deployer "$RELEASE_DIR/device-controller-win32-x64.zip" root@172.26.70.167:/srv/sftp/test/release); then
  echo "Failed to upload artifacts"
  cd "$CURRENT_DIR" || exit 1
  exit 1
fi

cd "$CURRENT_DIR" || exit 1
