#!/usr/bin/env sh

docker rm -f hare.database

if ! (docker run -d --name hare.database --restart always -p 5444:5432 -e POSTGRES_USER=dbadmin -e POSTGRES_PASSWORD=highsoft postgres:14); then
  echo "Failed to start database service"
  exit 1
fi

echo "Waiting database service to start..."
sleep 3

if ! (docker exec hare.database psql -U dbadmin -c "create database hare"); then
  echo "Failed to create main database"
  exit 1
fi

if ! (docker exec hare.database psql -U dbadmin -c "create database hare_adapter"); then
  echo "Failed to create adapter database"
  exit 1
fi

echo "Local dev environment setup completed, enjoy please!"
