#!/usr/bin/env sh

docker rm -f lockers.database

if ! (docker run -d --name lockers.database --restart always -p 5434:5432 -e POSTGRES_USER=dbadmin -e POSTGRES_PASSWORD=highsoft postgres:14); then
  echo "Failed to start database service"
  exit 1
fi

echo "Waiting database service to start..."
sleep 3

if ! (docker exec lockers.database psql -U dbadmin -c "create database lockers"); then
  echo "Failed to create main database"
  exit 1
fi

if ! (docker exec lockers.database psql -U dbadmin -c "create database lockers_adapter"); then
  echo "Failed to create adapter database"
  exit 1
fi

echo "Local dev environment setup completed, enjoy please!"
